2.03 description in doc link 357
IATI/IATI-Extra-Documentation pull request #392
Opened 2018-01-11 12:30 UTC by amy-silcock

Adding Extra Documentation as per: https://github.com/IATI/IATI-Schemas/issues/357

2018-01-26 16:12 UTC, PetyaKangalova approved these changes

2018-01-29 15:38 UTC, amy-silcock reviewed
@PetyaKangalova Looks good

2018-02-09 12:50 UTC, dalepotter commented
Changed base branch in order to force a refresh to the commit and file diff. This PR previously included changes already in the base branch.

2018-02-09 12:55 UTC, dalepotter requested changes

2018-02-09 12:55 UTC, dalepotter commented on .gitignore
> +en/activity-standard/activity-standard-example-annotated.xml
I'm not quite sure why this file has been added to `.gitignore`...?

2018-02-09 12:58 UTC, dalepotter requested changes

2018-02-09 12:58 UTC, dalepotter commented on en/organisation-standard/iati-organisations/iati-organisation/document-link.rst
> +2.03
I think the convention is to list changes reverse-chronologically - so here the `2.03` change would be listed before the `1.02` change.

2018-02-09 14:27 UTC, dalepotter approved these changes

2018-02-09 14:31 UTC, merged